FROM python:3.12.1-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /service

RUN apt update -y && \
    apt install -y python3-dev \
    gcc \
    musl-dev \
    libpq-dev \
    nmap

COPY pyproject.toml .

RUN pip install --upgrade pip
RUN pip install poetry

RUN poetry config virtualenvs.create false
RUN poetry install --no-root --no-interaction --no-ansi

COPY src src
COPY manage.py .

EXPOSE 8080

CMD sh -c 'poetry run python3 manage.py migrate --no-input && \
           poetry run python3 manage.py createadmin && \
           poetry run python3 manage.py collectstatic --noinput && \
           poetry run python3 manage.py runserver 0.0.0.0:8080'
# CMD python manage.py migrate && uvicorn project.asgi:application --reload --host 0.0.0.0 --port 8080 --lifespan off