# Generated by Django 5.0.6 on 2024-07-14 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "size",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("image_url", models.ImageField(max_length=255, upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(10)
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pizzas",
                        to="pizzas.category",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        related_name="pizzas", to="pizzas.size"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pizzas", to="pizzas.type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pizza",
                "verbose_name_plural": "Pizzas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["slug"], name="pizzas_pizz_slug_fde9b2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"],
                        name="pizzas_pizz_created_66094a_idx",
                    ),
                ],
            },
        ),
    ]
